# Generated by Django 4.1.6 on 2023-02-26 15:32

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year')),
                ('home', ckeditor.fields.RichTextField()),
                ('business', ckeditor.fields.RichTextField()),
                ('sport', ckeditor.fields.RichTextField()),
                ('technology', ckeditor.fields.RichTextField()),
                ('health', ckeditor.fields.RichTextField()),
                ('politika', ckeditor.fields.RichTextField()),
                ('news_photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/')),
                ('sport_photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/')),
                ('bisiness_photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/')),
                ('health_photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/')),
                ('politika_photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/')),
                ('technology_photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/')),
                ('news_title', models.CharField(max_length=255)),
                ('sport_title', models.CharField(max_length=255)),
                ('healh_title', models.CharField(max_length=255)),
                ('business_title', models.CharField(max_length=255)),
                ('technology_title', models.CharField(max_length=255)),
                ('politika_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
