# Generated by Django 4.1.6 on 2023-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='news_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/'),
        ),
    ]
