# Generated by Django 4.1.6 on 2023-03-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatesite', '0002_post_news_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='news_photo',
        ),
    ]
